title: Pushy
description: >
  A Java library for sending APNs (iOS/OS X/Safari) push notifications
project_url: "https://github.com/relayrides/pushy"
license_name: MIT License
license_url: "https://github.com/relayrides/pushy/blob/master/LICENSE.md"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
